### ISSUE TITLE
Alternative Collector/Client

### ISSUE THREAD

**Issue by nblumhardt** [influxdata/influxdb-csharp-obsolete#3]
Hi @beckettsean and co.

I'm maintaining a much more limited, but currently working and updated, client in C# at https://github.com/nblumhardt/influxdb-lineprotocol.

It's collection-only, i.e. there's no query support, but for enabling InfluxDB use in .NET apps _getting data in_ is currently the first hurdle to leap.

I am not investing a lot of time in development, but it's had a few PRs and over time I think it should be generally useful.

I'm raising this ticket because things would move faster if hosted over here: if you're still interested in shipping a C# client library I'd happily transfer it over to the influxdata org and continue patching/reviewing PRs as needed.

Alternatively, I could instead PR a link back to the other repo from the README here.

No problem for me either way, but thought I'd put it out there since this library seems to be in suspended animation :-)

All the best,
Nick

**Comment by beckettsean** [comment]
@nblumhardt thanks for the offer! 

@toddboom @pauldix seems like a good idea to me, since no one is maintaining the current C# repo. Should we replace the code in this repo with @nblumhardt's or should we delete this repo and migrate nblumhardt/influxdb-lineprotocol into the influxdata account? (My preference would be delete and migrate.)

**Comment by pauldix** [comment]
If this one hasn't been updated to work with the 0.9 API then I say delete and migrate sounds good.

**Comment by pauldix** [comment]
although I would prefer to have csharp in the name instead of `lineprotocol`

**Comment by nblumhardt** [comment]
Cool. Yes, the naming is a bit obscure, will sort that out.

Here's a possible plan:

 - [ ] Rename the `influxdb-lineprotocol` repo to `influxdb-csharp` (I can do this now)
 - [ ] Delete or rename (`influxdb-csharp-0.9` or `-obsolete`) this repository
 - [ ] Transfer the newer repo
 - [ ] Add `influxdata` as an owner of the packages on [NuGet](https://nuget.org)

I can keep the current CI build running for the time being; in the future it might make sense to move this to whatever CI platform the other projects here are using.

From there, we can deal with package renames etc. via further issues/PRs as the libs evolve.

Sound good?

**Comment by nblumhardt** [comment]
Rename is done; I can't kick off the transfer while there's a conflicting `influxdb-csharp` under `influxdata`. Cheers!

**Comment by beckettsean** [comment]
@nblumhardt I will handle the details next week.

**Comment by nblumhardt** [comment]
@beckettsean how's the week treating you? :-)

**Comment by beckettsean** [comment]
Busy! I've still got this on my list and I have lots of time tomorrow afternoon.

**Comment by nblumhardt** [comment]
Awesome, thanks for the update.

**Comment by beckettsean** [comment]
@nblumhardt @toddboom 

I renamed the old repo to influxdb-csharp-obsolete. 

@nblumhardt can you transfer your repo into the InfluxData account now, or do I need to do some user magic first? I'll certainly make a Team with you as Owner for the repo once it's in our account, but I believe I have to wait until the repo exists in our account. (And I don't want to create a dummy repo that would conflict with your transfer.)

**Comment by nblumhardt** [comment]
Hi @beckettsean - that's great, thanks.

I can't transfer the repository directly, because I'm not an admin of `influxdata` (just discovered this), so I've transferred it to you as an intermediate hop (user-to-user transfers are okay). You'll need to accept at your end.

If you can then forward it on (_Settings_ > _Transfer_) to `influxdata` all should be well.

It's a Saturday morning here so I'm on-and-offline, let me know if you hit any snags and I'll try to help out ASAP.

Cheers!

**Comment by nblumhardt** [comment]
(If someone else would be a better intermediary BTW just let me know - you can cancel/I'll re-transfer if need be.)

**Comment by beckettsean** [comment]
@nblumhardt It should be all set now. I've transferred the repo into the InfluxData organization and I created a new team "C-Sharp" that has full admin control over both the obsolete repo and the one you just transferred to our org. You have an invitation to be an admin of that Team. Once you accept that, you should have all the access you need.

If you need anything holler for me or for @toddboom

**Comment by nblumhardt** [comment]
Thanks @beckettsean that's great, all done.

Is there a https://www.nuget.org account I can add as package owner? //cc @toddboom

**Comment by beckettsean** [comment]
@nblumhardt glad everything is worked out, thanks again!

I don't know anything about NuGet, but I don't see it in our list of accounts. @toddboom is your key contact for that, though.
